### ISSUE TITLE
Installation/Compilation problem MAC Mojave

### ISSUE THREAD

**Issue by MartinSel** [prafols/rMSIproc#5]
I´d like to run the rMSI environment of a macOS Mojave system, but having trouble installing the rMSIproc package (rMSI installation without problems).
Using HOMEBREW I have installed FFTW and BOOST.
The error I get seems to be related to compilation and in more detail to the linking made during compilation.

Command in R studio:  
`devtools::install_github("prafols/rMSIproc", ref = "0.2")`

Error message:
`clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -lboost_thread -fPIC  -Wall -g -O2  -c threadingmsiproc.cpp -o threadingmsiproc.o`
**clang: warning: -lboost_thread: 'linker' input unused [-Wunused-command-line-argument]**
`clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rMSIproc.so RcppExports.o labelfreealign.o mtaverage.o mtbitdepthreduction.o mtlabelfreealign.o mtpeakpicking.o mtreplacezeropeaks.o mtsmoothing.o noiseestimation.o peakbinning.o peakmatrixio.o peakpicking.o rmsicdataio.o smoothing.o threadingmsiproc.o -lboost_thread -lfftw3 -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation`
**ld: library not found for -lboost_thread**
**clang: error: linker command failed with exit code 1 (use -v to see invocation)**
**make: ... [rMSIproc.so] Error 1**
**ERROR: compilation failed for package ‘rMSIproc’**
** removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rMSIproc’**
**Error: Failed to install 'rMSIproc' from GitHub:**

How can I resolve this issue?
Is it generally possible to run the rMSI environment on a macOS?

Thank you!

**Comment by prafols** [comment]
We do not have any MAC to perform testing of rMSItools on macOS but it should work because all libraries we use are cross platform. Since no one in my lab is a MAC owner I will need a bit of your help to fix this issue.
According to this: https://github.com/JakobEngel/dso/issues/26 it seams to be an a naming issue on MAC: instead of boost_thread they call it boost_thread-mt. Can you check this?

$ brew info boost

Then, if you have boost correctly installed you can test rebuilding the rMSIproc package from source by modifying the src/Makevars file: replace the -lboost_thread statement by -lboost_thread-mt.

Let me know if you need further help on this and please let me know if it works so I can modify the code to make it compatible with MAC,

Best

Pere

**Comment by MartinSel** [comment]
Hello Pere,

thank you very much for your input!
Changing the boost_thread to boost_thread-mt in the scr/Makevars file resolved the issue and allowed me to install rMSIproc on MAC OS Mojave.

Best regards
Martin

**Comment by prafols** [comment]
Hi Martin,
I'm glad to heard that helped. I also would like to let you know that in the current development version we removed the boost dependency and used C++11 threads instead (now it is completely supported in R). Therefore, the next version of rMSIproc will be easier to install in MAC.

Best,
Pere
